language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
before_deploy:
  - mv target/release/ccs "target/release/ccs-$TRAVIS_TAG-$TRAVIS_OS_NAME"
script: 
  - cargo build --release
  - cargo test
deploy:
  - provider: releases
    cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/ccs-*
    token:
      - ${API_KEY}